clc;
clearvars;
define_constants
A={'case118',...
    'case2746wp',...
    'case14',...    
    'case30',...
    'case39',...
    'case9target',...
    'case2383wp',...
    'case4gs',...
    'case_ieee30',...
    'case24_ieee_rts',...
    'case5',....
    'case2736sp',...
    'case30Q',...
    'case57',...
    };
for it=1:length(A)
    casename=A{it};
    disp(casename);    
mpc=loadcase(casename);

Y=makeYbus(mpc);
Y=imag(Y);

mpc.branch(:,BR_X)=1./Y(sub2ind(size(Y),mpc.branch(:,1),mpc.branch(:,2)));

mpc.branch(:,BR_R)=0;

mpc.branch(:,BR_B)=0;

casename=strcat('Cases/',casename,'lossless.m');

savecase(casename,mpc);
end

save('caselist.mat','A');