function [Qse,Qbr,V]=FormQuads(mpc,gam,del)
define_constants;
pv  =   find(mpc.bus(:,BUS_TYPE)==2);
pq  =   find(mpc.bus(:,BUS_TYPE)==1);
nsb =   (~(mpc.bus(:,BUS_TYPE)==3));
sb  =   find(~nsb);
npv =   length(pv);
npq =   length(pq);
nbr =   size(mpc.branch,1);
nbus=   size(mpc.bus,1);
bi  =   mpc.branch(:,1);
bj  =   mpc.branch(:,2);
Qse =   cell(npv,1);
Qbr =   cell(6*nbr+2*npq,1);
Vmin=   mpc.bus(:,13);
Vmax=   mpc.bus(:,12);
v   =   (nbus-1+npq)+reshape(1:(2*(nbus-1)),[nbus-1,2]);
V   =   cell(nbus,2);
V(nsb,:)    =   arrayfun(@(anyx) {num2str(anyx)},v);
V{sb,1}     =   mpc.bus(sb,VM)*1;
V{sb,2}     =   mpc.bus(sb,VM)*0;
for it=1:npv
    Qse{it}  =   {V(pv(it),1),V(pv(it),1),1;...
        V(pv(it),2),V(pv(it),2),1;...
        {num2str(0)},{num2str(0)},-mpc.bus(pv(it),VM).^2};
end
for it=1:nbr
    i   =   bi(it);
    j   =   bj(it);
    Qbr{6*(it-1)+1} =   {V(i,1),V(j,1),1;...
                 V(i,2),V(j,2),1;...
                 V(i,1),V(i,1),-gam*cos(del);...
                 V(i,2),V(i,2),-gam*cos(del);};
    Qbr{6*(it-1)+2} =   {V(i,1),V(j,1),1;...
                 V(i,2),V(j,2),1;...
                 V(j,1),V(j,1),-gam*cos(del);...
                 V(j,2),V(j,2),-gam*cos(del);};
    Qbr{6*(it-1)+3} =   {V(i,1),V(j,2),1;...
                 V(i,2),V(j,1),-1;...
                 V(j,1),V(j,1),sin(del)/gam;...
                 V(j,2),V(j,2),sin(del)/gam;};
    Qbr{6*(it-1)+4} =    {V(i,1),V(j,2),1;...
                 V(i,2),V(j,1),-1;...
                 V(i,1),V(i,1),sin(del)/gam;...
                 V(i,2),V(i,2),sin(del)/gam;};
    Qbr{6*(it-1)+5} =   {V(i,1),V(j,2),-1;...
                 V(i,2),V(j,1),1;...
                 V(i,1),V(i,1),sin(del)/gam;...
                 V(i,2),V(i,2),sin(del)/gam;};
    Qbr{6*(it-1)+6} =   {V(i,1),V(j,2),-1;...
                 V(i,2),V(j,1),1;...
                 V(j,1),V(j,1),sin(del)/gam;...
                 V(j,2),V(j,2),sin(del)/gam;};
end
%{
for it=1:nbr
    i   =   bi(it);
    j   =   bj(it);
     Qbr{nbr+it} =   {V(i,1),V(j,1),1;...
                 V(i,2),V(j,2),1;...
                 V(j,1),V(j,1),-gam;...
                 V(j,2),V(j,2),-gam};
end
%}
for it=6*nbr+(1:npq)
    i   =   pq(it-6*nbr);
    Qbr{it} =   {V(i,1),V(i,1),1;...
                 V(i,2),V(i,2),1;...
                 {num2str(0)},{num2str(0)},-Vmin(i).^2;};
    Qbr{npq+it} =   {V(i,1),V(i,1),-1;...
                 V(i,2),V(i,2),-1;...
                 {num2str(0)},{num2str(0)},Vmax(i).^2;};
end
end